apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SERVICE_NAME}-config
  namespace: ${NAMESPACE}
data:
  REPL_DOCMOSIS_BACKEND_URL: "http://ethos-repl-docmosis-service-saat.service.core-compute-saat.internal"
  ENVIRONMENT_NAME: "saat"
  TORNADO_URL: "http://tornado:8090/rs/render"
  TORNADO_ACCESS_KEY: ""
  IDAM_API_URL: "http://sidam-api:5000"
  IDAM_API_JWK_URL: "http://sidam-api:5000/jwks"
  CCD_DATA_STORE_API_URL: "http://ccd-data-store-api:4452"
  DOCUMENT_MANAGEMENT_URL: "http://dm-store:8080"
  SERVICE_AUTH_PROVIDER_URL: "http://service-auth-provider-api:8080"
  CCD_GATEWAY_BASE_URL: "http://127.0.0.1:3453"
  ETHOS_REPL_SERVICE_S2S_SECRET: ${ETHOS_REPL_SERVICE_S2S_SECRET}
  MICRO_SERVICE: ${MICRO_SERVICE}