apiVersion: v2
name: ethos-repl-docmosis-backend
home: https://github.com/hmcts/ethos-repl-docmosis-service
version: 0.4.26
description: HMCTS Ethos Replacement Docmosis Service
maintainers:
  - name: HMCTS ETHOS Team
dependencies:
  - name: java
    version: 5.3.1
    repository: 'oci://hmctspublic.azurecr.io/helm'
