apiVersion: v2
name: ethos-repl-docmosis-backend
home: https://github.com/hmcts/ethos-repl-docmosis-service
version: 0.4.22
description: HMCTS Ethos Replacement Docmosis Service
maintainers:
  - name: HMCTS ETHOS Team
dependencies:
  - name: java
    version: 5.2.0
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
